export const MOCK_SCHOOLS = [
  {
    id: "1",
    name: "Al-Nour International School",
    code: "ANS-001",
    email: "info@alnour.edu",
    phone: "+20-2-1234-5678",
    address: "12 Nile Corniche St, Maadi",
    city: "Cairo",
    state: "Cairo",
    country: "Egypt",
    website: "https://alnour.edu",
    timezone: "Africa/Cairo",
    status: "active",
  },
  {
    id: "2",
    name: "Madrasa Al-Mustaqbal",
    code: "MAM-002",
    email: "admin@mustaqbal.edu.sa",
    phone: "+966-11-987-6543",
    address: "45 King Fahd Road",
    city: "Riyadh",
    state: "Riyadh",
    country: "Saudi Arabia",
    website: "https://mustaqbal.edu.sa",
    timezone: "Asia/Riyadh",
    status: "active",
  },
  {
    id: "3",
    name: "Academy of Sciences",
    code: "AOS-003",
    email: "contact@academyos.ae",
    phone: "+971-4-555-1234",
    address: "Business Bay, Tower 7",
    city: "Dubai",
    state: "Dubai",
    country: "UAE",
    website: "https://academyos.ae",
    timezone: "Asia/Dubai",
    status: "active",
  },
  {
    id: "4",
    name: "Green Valley School",
    code: "GVS-004",
    email: "gvs@greenvalley.edu.kw",
    phone: "+965-2234-5678",
    address: "Block 5, Green District",
    city: "Kuwait City",
    state: "Hawalli",
    country: "Kuwait",
    website: "https://greenvalley.edu.kw",
    timezone: "Asia/Kuwait",
    status: "inactive",
  },
  {
    id: "5",
    name: "Al-Rashid Educational Institute",
    code: "REI-005",
    email: "info@alrashid.edu.qa",
    phone: "+974-4444-5555",
    address: "Education City, Building C",
    city: "Doha",
    state: "Doha",
    country: "Qatar",
    website: "https://alrashid.edu.qa",
    timezone: "Asia/Qatar",
    status: "active",
  },
];

export const MOCK_STATS = {
  total_schools: 5,
  total_users: 1243,
  total_students: 847,
  total_teachers: 96,
  total_classes: 42,
  active_subscriptions: 4,
};

export const MOCK_SUBSCRIPTIONS = [
  {
    id: "sub-1",
    schoolId: "1",
    schoolName: "Al-Nour International School",
    tier: "premium",
    billingCycle: "annually",
    status: "active",
    startDate: "2025-09-01",
    expiryDate: "2026-08-31",
    amount: 2388,
    currency: "USD",
  },
  {
    id: "sub-2",
    schoolId: "2",
    schoolName: "Madrasa Al-Mustaqbal",
    tier: "basic",
    billingCycle: "monthly",
    status: "active",
    startDate: "2025-10-01",
    expiryDate: "2026-09-30",
    amount: 99,
    currency: "USD",
  },
  {
    id: "sub-3",
    schoolId: "3",
    schoolName: "Academy of Sciences",
    tier: "enterprise",
    billingCycle: "annually",
    status: "active",
    startDate: "2025-01-01",
    expiryDate: "2025-12-31",
    amount: 4800,
    currency: "USD",
  },
  {
    id: "sub-4",
    schoolId: "4",
    schoolName: "Green Valley School",
    tier: "free",
    billingCycle: "monthly",
    status: "trial",
    startDate: "2026-04-01",
    expiryDate: "2026-06-30",
    amount: 0,
    currency: "USD",
  },
  {
    id: "sub-5",
    schoolId: "5",
    schoolName: "Al-Rashid Educational Institute",
    tier: "premium",
    billingCycle: "annually",
    status: "active",
    startDate: "2025-08-01",
    expiryDate: "2026-07-31",
    amount: 2388,
    currency: "USD",
  },
];

export const MOCK_ANALYTICS = {
  overview: {
    totalSchools: 5,
    activeSchools: 4,
    totalRevenue: 9675,
    totalUsers: 1243,
    totalStudents: 847,
    totalTeachers: 96,
  },
  // month is 0-indexed (0=Jan) for Intl.DateTimeFormat
  schoolGrowth: [
    { monthIndex: 0, schools: 2 },
    { monthIndex: 1, schools: 2 },
    { monthIndex: 2, schools: 3 },
    { monthIndex: 3, schools: 3 },
    { monthIndex: 4, schools: 4 },
    { monthIndex: 5, schools: 5 },
  ],
  recentActivity: [
    {
      id: "a1",
      type: "school_created",
      messageKey: "activity_school_created",
      name: "Al-Rashid Educational Institute",
      timeKey: "time_2h",
    },
    {
      id: "a2",
      type: "subscription_upgraded",
      messageKey: "activity_subscription_upgraded",
      name: "Al-Nour International School",
      timeKey: "time_1d",
    },
    {
      id: "a3",
      type: "credentials_sent",
      messageKey: "activity_credentials_sent",
      name: "Academy of Sciences",
      timeKey: "time_2d",
    },
    {
      id: "a4",
      type: "school_activated",
      messageKey: "activity_school_activated",
      name: "Madrasa Al-Mustaqbal",
      timeKey: "time_3d",
    },
    {
      id: "a5",
      type: "subscription_created",
      messageKey: "activity_subscription_created",
      name: "Green Valley School",
      timeKey: "time_1w",
    },
  ],
};
